added control in nginx for deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -158,9 +158,18 @@ jobs:
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.PRIVATE_KEY }}
           script: |
+
+            rm -f /etc/nginx/sites-enabled/nginx.conf
+            ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled/nginx.conf
+
             sed -i "s/localhost/${{ secrets.DOMAIN }}/g" /etc/nginx/sites-available/nginx.conf
             ln -s /etc/nginx/sites-available/nginx.conf /etc/nginx/sites-enabled
-            nginx -t && sudo systemctl restart nginx
+            if nginx -t; then
+              sudo systemctl restart nginx
+            else
+              echo "Nginx configuration test failed. Deployment aborted."
+              exit 1
+            fi
 
       # Step 6: Certbot per SSL
       - name: Setup Certbot for SSL
